# Generated by Django 2.0.1 on 2018-04-13 23:00

from django.db import migrations, models
import rater.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mandarin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', rater.models.MinMaxFloat()),
                ('round', rater.models.MinMaxFloat()),
                ('smooth', rater.models.MinMaxFloat()),
                ('soft', rater.models.MinMaxFloat()),
                ('elasticity', rater.models.MinMaxFloat()),
                ('orange', rater.models.MinMaxFloat()),
                ('smell', rater.models.MinMaxFloat()),
                ('hand_smell', rater.models.MinMaxFloat()),
                ('beautiful', rater.models.MinMaxFloat()),
                ('trump', rater.models.MinMaxFloat()),
                ('brown', rater.models.MinMaxFloat()),
                ('mold', rater.models.MinMaxFloat()),
                ('hand_feel', rater.models.MinMaxFloat()),
                ('spot_depth', rater.models.MinMaxFloat()),
                ('skin_thick_before', rater.models.MinMaxFloat()),
                ('temperature', rater.models.MinMaxFloat()),
                ('damage', rater.models.MinMaxFloat()),
                ('symmetrical', rater.models.MinMaxFloat()),
                ('plastic', rater.models.MinMaxFloat()),
                ('stem_loose', rater.models.MinMaxFloat()),
                ('opening', rater.models.MinMaxFloat()),
                ('skin_thick_after', rater.models.MinMaxFloat()),
                ('slice_size', rater.models.MinMaxFloat()),
                ('pith_amount', rater.models.MinMaxFloat()),
                ('pith_color', rater.models.MinMaxFloat()),
                ('seeds', rater.models.MinMaxFloat()),
                ('taste', rater.models.MinMaxFloat()),
            ],
        ),
    ]
