# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateMandarin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroOfRate', models.IntegerField()),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.Mandarin')),
            ],
        ),
    ]
