# Generated by Django 2.0.4 on 2018-04-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandarine', '0002_auto_20180414_0848'),
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandarin',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandarin',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mandarine.UserProfile'),
        ),
    ]
