# Generated by Django 2.0.4 on 2018-04-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0002_auto_20180414_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandarin',
            name='name',
            field=models.CharField(default='mandarin', max_length=20),
        ),
    ]
