# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_auto_20180414_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratemandarin',
            name='rate',
        ),
        migrations.DeleteModel(
            name='RateMandarin',
        ),
    ]
