# Generated by Django 2.0.4 on 2018-04-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandarine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandarin',
            name='owner',
        ),
        migrations.DeleteModel(
            name='testi',
        ),
        migrations.DeleteModel(
            name='Mandarin',
        ),
    ]
